### PR TITLE
Yo-Scale fix

### PR DESCRIPTION
**Pull request by VanStorm**
- increased number of scales
- moved pentatonic minor & major scale one up to account for the new scale

### CODE REVIEW

**Comment by xSimone** [comment]
Possible to download a test version with this commit? 

Copied the contents into the relevant file and edited it, it didn't work. :f

**Comment by VanStorm** [comment]
sure i put up a release to test:
https://github.com/VanStorm/ShawzinBot/releases

**Comment by xSimone** [comment]
This is an AWESOME start. It's not 100% of a fix, some notes are incorrect, but 90% of the midi plays correctly now. 

Something wrong with higher notes, but the switching of the scales now works flawlessly. ;x

Well done. ;d <3

**Comment by VanStorm** [comment]
I will look into that too :)

EDIT: okay I have to admit I have no idea why the higher notes are off. The "yo-scale" is the 6th scale (starting to count with 0 for the chromatic scale), pentatonic minor the 7th and pentatonic major the 8th scale. Before the introduction pentatonic minor was the 6th scale and pentatonic major the 7th scale.

**Comment by aembur** [comment]
The Yo scale also includes G#4, now playable without the use of Whammy.

`{ 68, new[] {6,2,3,0} }, // G#4`

**Comment by VanStorm** [comment]
@aembur included that. Ty for pointing that out :)

**Comment by ianespana** [comment]
I'll give this a test before merging it. Thanks for your help!

**Comment by VanStorm** [comment]
@ianespana no problem. Haven't found out what's wrong with the higher notes mentioned.

> 
> 
> This is an AWESOME start. It's not 100% of a fix, some notes are incorrect, but 90% of the midi plays correctly now.
> 
> Something wrong with higher notes, but the switching of the scales now works flawlessly. ;x
> 
> Well done. ;d <3

**Comment by ianespana** [comment]
@xSimone What exactly is wrong with the higher notes? They seem to work just fine. The only issue is B5 which still isn't anywhere on the current scales, so it sounds like C5

**Comment by Rareat** [comment]
@ianespana Stairway to heaven and thunderstruck sound a bit muffled, compared to before, don't think the 30 note cap that was added has anything to do with that tho, as there are barely 5-10 per sec

**Comment by ianespana** [comment]
@Rareat You mean, compared to the autohotkey version or this version?

**Comment by ianespana** [comment]
Alright, tested it and it works like a charm. Will publish a binary soon

**Comment by Rareat** [comment]
@ianespana to the other version, but i guess it's game related. Just did some tests with the midis. moved the side melody notes a bit, It worked but it sounds awful. Guess it's because the notes are on different scales, so it doesn't manage to play them at the same time,  but it used to work, so i can only guess it's warframe related atm.

**Pull request merged**
