### PR TITLE
Program writes keys to window.

### PR DESCRIPTION
**Pull request by lilggamegenius**
Currently requires the user to manually focus
the window before input is registered.

Signed-off-by: Gabe Gonzalez <lilggamegenius@gmail.com>

### CODE REVIEW

**Comment by ianespana** [comment]
I actually think manual focus isn't a bad thing to be honest. It'd be annoying if the script tried to focus the window every time.
The only part that might break is scale changing, but we can get around that easily

**Comment by ianespana** [comment]
Interesting... Quick question, are you running Warframe in fullscreen or in windowed mode @lilggamegenius ?
Just tried the window to foreground on my end and it worked without issues while running Warframe in windowed mode

**Comment by lilggamegenius** [comment]
That's odd, I was using windowed mode and i had to manually click to enable. I forgot to test if it does this in fullscreen mode or not. It might have been because i had my controller connected and i think it default to the controller when one is connected.

**Comment by lilggamegenius** [comment]
Also i forgot to mention, [This is where I got the library to send key and mouse input](https://www.codeproject.com/Articles/117657/InputManager-library-Track-user-input-and-simulate).

**Comment by ianespana** [comment]
Alright, so, I've made huge progress and I have (almost) all the keys working now. I just need to figure out the input devices and we're good to release!

**Comment by lilggamegenius** [comment]
Seems like the standard library has support for Midi devices https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi
This code should get the list of devices
```csharp
    string midiInputQueryString = MidiInPort.GetDeviceSelector();
    DeviceInformationCollection midiInputDevices = await DeviceInformation.FindAllAsync(midiInputQueryString);
```

**Comment by ianespana** [comment]
I'm already getting the devices with the DryWetMidi library (https://github.com/melanchall/drywetmidi), but it doesn't give you any more data when an input happens other than telling you it happened...

**Comment by ianespana** [comment]
I'll push my changes so you can have a look as well

**Pull request merged**
